### ISSUE TITLE
How to Work With MongoDB New Version

### ISSUE THREAD

**Issue by basantk** [thephpleague/monga#40] opened 2017-03-17 07:56 UTC
How connection with mongoDB instance instead of MongoClient. Please help.

MongoDB\Driver\Manager() instead MongoClient(). in Monga

**Comment by bcrowe** [comment] 2017-03-20 14:37
Duplicate of https://github.com/thephpleague/monga/issues/36 ... will move discussion over there.

**Closed as completed by bcrowe** 2017-03-20 14:37 UTC
